### PR TITLE
merging second into master to request code review 

### PR DESCRIPTION
**Pull request by memelopez**
the NWT clone we did is finished.

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

- [ ] Please kindly open just one PR for code review(for next time), it makes code review easier and better
- [x] Fix the linter errors 

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by memelopez** [comment]
sorry about making another PR. Thanks for letting us know that one PR is the best way to go. We fixed the issues and we are ready for another code review 👍🏼

> ## Hi Team 
> #### Great Job so far, everything works fine, but there are a few more things required.
> ### General
> * [x]  Please kindly open just one PR for code review(for next time), it makes code review easier and better
> * [x]  Fix the linter errors
> 
> ### Make changes and submit another code review request.
> _Happy coding_
> (Any questions Feel free to contact me on slack @kobiyoyo)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General


- [x] You have conflicting files you need to fix


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by memelopez** [comment]
had to pull the code from the 'second' branch to solve the merge issues 🙈 sorry about that... I tried other ways of fixing it besides this way but was not any good.

**Review by descholar-ceo — COMMENTED** [review]
# Status: Invalid Submission :x: :disappointed: :stop_sign: 
## Hello @memelopez and @kensayo   :handshake: :handshake: :handshake: 

Thank you for submitting a code review request. And congratulations on that you have completed this project. However your code review request is marked as invalid due to the following reasons:

1. The submitted Pull Request is already merged.

_`Action to be taken:` While you are preparing for the other code review request submission, we need you to submit an open Pull Request which is open => (not merged and not closed)_

Happy coding!!!
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by descholar-ceo — COMMENTED** [review]
.

**Review by descholar-ceo — COMMENTED** [review]
,

**Pull request merged**
